services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      TZ: UTC
    network_mode: host
    volumes:
      - ./configs/config.yaml:/app/configs/config.yaml:ro
